### ISSUE TITLE
OpenAC.Net.DFe.Core.OpenDFeException: 'Número de série obrigatório.'

### ISSUE THREAD

**Issue by transis2** [OpenAC-Net/OpenAC.Net.NFSe#115]
Está dando esse erro no GetClient para o provedor IPM.
Não testei com outros

![image](https://user-images.githubusercontent.com/4941173/186517509-9257e441-6ba3-415c-b818-e75284d01a93.png)

**Comment by transis2** [comment]
at OpenAC.Net.DFe.Core.CertificadoDigital.SelecionarCertificado(String cerSerie)
   at OpenAC.Net.NFSe.Providers.ProviderBase.get_Certificado() in /_/src/OpenAC.Net.NFSe/Providers/ProviderBase.cs:line 211
   at OpenAC.Net.NFSe.Providers.NFSeRestServiceClient..ctor(ProviderBase provider, TipoUrl tipoUrl) in /_/src/OpenAC.Net.NFSe/Providers/NFSeRestServiceClient.cs:line 57
   at OpenAC.Net.NFSe.Providers.IPMServiceClient..ctor(ProviderBase provider, TipoUrl tipoUrl) in /_/src/OpenAC.Net.NFSe/Providers/IPM/IPMServiceClient.cs:line 43
   at OpenAC.Net.NFSe.Providers.ProviderIPM.GetClient(TipoUrl tipo) in /_/src/OpenAC.Net.NFSe/Providers/IPM/ProviderIPM.cs:line 62
   at OpenAC.Net.NFSe.Providers.ProviderBase.ConsultarLoteRps(Int32 lote, String protocolo, NotaServicoCollection notas) in /_/src/OpenAC.Net.NFSe/Providers/ProviderBase.cs:line 505

**Comment by transis2** [comment]
Estou usando as aplicações com .net 4.7.2
Como faço para optar por esse framework ao invés do .net core 6 ?

**Comment by rftd** [comment]
Do mesmo jeito que sempre usou o que mudou foi o demo e não a biblioteca.

**Comment by rftd** [comment]
e o erro ai é que tu não informou os dados do certificado, quando a dll esta rodando em .net standard não tem a tela de seleção de certificados.

**Comment by transis2** [comment]
Boa, valeu
